language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose down
  - docker image prune --all   
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy khoalnn/reverseproxy
  - docker tag udagram-api-user khoalnn/udagram-api-user  
  - docker tag udagram-api-feed khoalnn/ udagram-api-feed   
  - docker tag udagram-frontend:local khoalnn/udagram-frontend

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "Lekho@2481990" | docker login -u "lekhoa2481990" --password-stdin
  - docker push khoalnn/reverseproxy
  - docker push khoalnn/udagram-api-user
  - docker tag  udagram-api-feed khoalnn/udagram-api-feed
  - docker push khoalnn/udagram-frontend