version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest # Use the latest Node.js Docker image

    steps:
      - checkout # Check out the code

      - run:
          name: Show Node.js version
          command: node --version # Display Node.js version for logging

      - run:
          name: Show Docker version
          command: docker --version # Verify Docker installation

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Docker Hub Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build Docker images
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend:v7 ./udagram-frontend
            docker build -t udagram-reverseproxy ./udagram-reverseproxy

      - run:
          name: Tag Docker images
          command: |
            docker tag udagram-api-feed:latest khoalnn/udagram-api-feed:latest
            docker tag udagram-api-user:latest khoalnn/udagram-api-user:latest
            docker tag udagram-frontend:v7 khoalnn/udagram-frontend:v7
            docker tag udagram-reverseproxy:latest khoalnn/reverseproxy:latest

      - run:
          name: Push Docker images
          command: |
            docker push khoalnn/udagram-api-feed:latest
            docker push khoalnn/udagram-api-user:latest
            docker push khoalnn/udagram-frontend:v7
            docker push khoalnn/reverseproxy:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
